"""Count controls must distinguish user actions from label refresh events."""
from types import ModuleType, SimpleNamespace as NS
import unittest
from unittest.mock import Mock
import numpy as np
from test_custom_feature import api_stub, load


class CountControlsTests(unittest.TestCase):
    def setUp(self):
        adsk = api_stub()
        self.state = NS(current_cp_count_upper=8, current_cp_count_lower=10,
                        fit_cache={'existing': True}, preview_graphics=None, needs_refit=False)
        logic = ModuleType('logic')
        logic.state = self.state
        self.module = load('count_controls_test', 'ui/handlers.py', {
            'adsk': adsk, 'adsk.core': adsk.core, 'adsk.fusion': adsk.fusion,
            'logic': logic, 'logic.fitter': NS(run_fitter=Mock()),
            'ui.dialog': NS(create_ui_inputs=Mock())})
        self.handler = self.module.AirfoilSplineCommandInputChangedHandler()
        self.controls = dict(initial_cp_count=NS(value=6), chord_line=NS(selectionCount=1),
                             file_path=NS(value='foil.dat'))
        self.inputs = NS(itemById=self.controls.get)
        owner = self
        class Button:
            def __init__(self, name, count):
                self.name, self._text, self.writes = name, f'  {count}', 0
            @property
            def text(self):
                return self._text
            @text.setter
            def text(self, text):
                self._text = text
                self.writes += 1
                # Model the nested input event generated by a UI property update.
                owner.handler.handle(None, owner.inputs, self.name)
        self.controls['cp_count_upper'] = Button('cp_count_upper', 8)
        self.controls['cp_count_lower'] = Button('cp_count_lower', 10)

    def counts(self):
        return self.state.current_cp_count_upper, self.state.current_cp_count_lower

    def test_initial_count_waits_for_reset(self):
        cached = self.state.fit_cache
        self.handler.handle(None, self.inputs, 'initial_cp_count')
        self.assertEqual(self.counts(), (8, 10))
        self.assertIs(self.state.fit_cache, cached)
        self.assertFalse(self.state.needs_refit)
        self.handler.handle(None, self.inputs, 'reset_button')
        self.assertEqual(self.counts(), (6, 6))
        self.assertTrue(self.state.needs_refit)
        self.assertEqual(self.state.fit_cache, {})

    def test_each_click_increments_only_its_surface_even_with_label_events(self):
        self.handler.handle(None, self.inputs, 'cp_count_upper')
        self.assertEqual(self.counts(), (9, 10))
        self.assertTrue(self.state.needs_refit)
        self.assertEqual(self.controls['cp_count_lower'].writes, 0)
        self.handler.handle(None, self.inputs, 'cp_count_lower')
        self.assertEqual(self.counts(), (9, 11))
        self.handler.handle(None, self.inputs, 'cp_count_upper')
        self.assertEqual(self.counts(), (10, 11))

    def test_preview_label_refresh_does_not_request_a_fit(self):
        self.controls['cp_count_upper']._text = 'old'
        self.controls['cp_count_lower']._text = 'old'
        self.module.update_cp_count_labels(self.inputs)
        self.assertEqual(self.counts(), (8, 10))
        self.assertFalse(self.state.needs_refit)
        self.module.update_cp_count_labels(self.inputs)
        self.assertEqual(self.controls['cp_count_upper'].writes, 1)
        self.assertEqual(self.controls['cp_count_lower'].writes, 1)

    def test_clicked_counts_reach_the_common_fitter_unchanged(self):
        from logic import feature_recipe
        x = (1 - np.cos(np.linspace(0, np.pi, 61))) / 2
        y = .6 * (.2969*np.sqrt(x)-.126*x-.3516*x*x+.2843*x**3-.1036*x**4)
        points = list(zip(x[::-1], y[::-1])) + list(zip(x[1:], -y[1:]))
        dat = 'foil\n' + '\n'.join(f'{a:.12f} {b:.12f}' for a, b in points)
        for button, expected in [('cp_count_upper', (9, 10)), ('cp_count_lower', (9, 11))]:
            self.handler.handle(None, self.inputs, button)
            upper, lower = self.counts()
            data = feature_recipe.fit_data(dict(dat=dat), dict(te=.02, smoothness=.001,
                upper_count=upper, lower_count=lower, continuity=2), 10)
            self.assertEqual((len(data['upper_cp_raw']), len(data['lower_cp_raw'])), expected)
            self.assertEqual((data['degree_u'], data['degree_l']), tuple(n-1 for n in expected))
